#include QMK_KEYBOARD_H

enum unicode_names {
    SNAKE,
    THUMBS_UP,
    SMILE,
    SAD,
    WINK,
    GREEN_TICK
};

const uint32_t PROGMEM unicode_map[] = {
    [SNAKE]  = 0x1F40D, // 🐍
    [THUMBS_UP] = 0x1F44D, // 👍
    [SMILE] = 0x1F642, // 🙂
    [SAD] = 0x2639, // ☹️
    [WINK] = 0x1f609, // 😉
    [GREEN_TICK] = 0x2705 // ✅
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_dactyl(
        KC_EQL, KC_1, KC_2, KC_3, KC_4, KC_5,
        KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T,
        LT(1, KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G,
        KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B,
        KC_NO, KC_GRV, KC_F13, KC_LEFT, KC_RGHT,

        KC_LCTL, KC_LALT, KC_HOME, KC_BSPC, KC_DEL, KC_END,

        KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS,
        KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS,
        KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
        KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
        KC_UP, KC_DOWN, KC_LBRC, KC_RBRC, KC_NO,

        KC_LGUI, KC_RCTL, KC_PGUP, KC_PGDN, KC_ENT, KC_SPC
    ),

    [1] = LAYOUT_dactyl(
        KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,
        MO(2), KC_VOLU, KC_MSTP, KC_MPLY, KC_BRIU, KC_PAUS,
        KC_TRNS, KC_VOLD, KC_MPRV, KC_MNXT, KC_BRID, KC_SLCK,
        KC_TRNS, KC_PERC, KC_CIRC,  KC_LBRC, KC_RBRC, KC_TILD,
        KC_NO, KC_INS, KC_TRNS, KC_TRNS, KC_TRNS,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

        KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
        KC_KP_ASTERISK, KC_7, KC_8, KC_9, KC_MINUS, KC_F12,
        KC_KP_SLASH, KC_4, KC_5, KC_6, KC_KP_PLUS, KC_NUMLOCK,
        KC_KP_EQUAL, KC_1, KC_2, KC_3, KC_KP_ENTER, KC_TRNS,
        KC_PSCR, KC_0, KC_KP_DOT, KC_KP_ENTER, KC_NO,

        X(SMILE), X(GREEN_TICK), X(WINK), X(SAD), X(THUMBS_UP), OSL(3)
    ),

    [2] = LAYOUT_dactyl(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_U, RESET, DEBUG,
        KC_TRNS, KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_BTN2,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY,
        KC_TRNS, KC_TRNS, KC_MPRV, KC_MNXT, KC_TRNS, KC_TRNS,
        KC_VOLU, KC_VOLD, KC_MUTE, KC_TRNS, KC_TRNS,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_WBAK
    ),

    [3] = LAYOUT_dactyl(
        KC_TRNS, X(SNAKE), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_BTN1, KC_BTN2,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_MPRV, KC_TRNS, KC_TRNS, KC_TRNS,
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,

        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
    )
};

